export const PERMISSIONS = {
  DASHBOARD_VIEW: "dashboard.view",
  PRODUCTS_VIEW: "products.view",
  CATEGORIES_VIEW: "categories.view",
  ORDERS_VIEW: "orders.view",
  CUSTOMERS_VIEW: "customers.view",
  STAFF_VIEW: "staff.view",
  STAFF_MANAGE: "staff.manage",
  DRIVERS_VIEW: "drivers.view",
  BILLING_VIEW: "billing.view",
  ENQUIRY_VIEW: "enquiry.view",
  OFFERS_VIEW: "offers.view",
  BRANDS_VIEW: "brands.view",
  NOTIFICATIONS_VIEW: "notifications.view",
  SETTINGS_VIEW: "settings.view",
  PROFILE_VIEW: "profile.view",
} as const;

export const PERMISSION_OPTIONS = [
  { key: PERMISSIONS.DASHBOARD_VIEW, label: "Dashboard" },
  { key: PERMISSIONS.PRODUCTS_VIEW, label: "Products" },
  { key: PERMISSIONS.CATEGORIES_VIEW, label: "Categories" },
  { key: PERMISSIONS.ORDERS_VIEW, label: "Orders" },
  { key: PERMISSIONS.CUSTOMERS_VIEW, label: "Customers" },
  { key: PERMISSIONS.STAFF_VIEW, label: "Staff" },
  { key: PERMISSIONS.DRIVERS_VIEW, label: "Drivers" },
  { key: PERMISSIONS.BILLING_VIEW, label: "Billing" },
  { key: PERMISSIONS.ENQUIRY_VIEW, label: "Enquiry" },
  { key: PERMISSIONS.OFFERS_VIEW, label: "Offers" },
  { key: PERMISSIONS.BRANDS_VIEW, label: "Brands" },
  { key: PERMISSIONS.NOTIFICATIONS_VIEW, label: "Notifications" },
  { key: PERMISSIONS.SETTINGS_VIEW, label: "Settings" },
  { key: PERMISSIONS.PROFILE_VIEW, label: "Profile" },
] as const;
