name: 🚀 Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/suggithota/website
            git pull origin main
            npm ci
            npm run build
            if pm2 describe suggi-website > /dev/null; then
              pm2 restart suggi-website --update-env
            else
              pm2 start npm --name "suggi-website" -- start
            fi
            pm2 save